version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing the dependencies"
      - apt-get update -y
      - apt-get install -y unzip
  pre_build:
    commands:
      - echo "Connecting to Docker registry"
      - aws --version
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 494713367427.dkr.ecr.eu-west-3.amazonaws.com
      - echo "Pre-build phase completed."
  build:
    commands:
      - echo "Building the code and Docker image"
      - docker build -t dhaneesh .
      - echo "docker image build completed"
  
  post_build:
    commands:
      - echo "change the tag of image"
      - docker tag dhaneesh:latest 494713367427.dkr.ecr.eu-west-3.amazonaws.com/dhaneesh:latest
      - docker push 494713367427.dkr.ecr.eu-west-3.amazonaws.com/docker:latest
